# Cash Flow PDF Generator
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, TableStyle
from datetime import datetime
import io

from utils.generator_core import (
    BaseReportGenerator, ReportColors, format_currency, get_nigerian_time,
    create_table, parse_date_safe, safe_float, format_tin_display, wrap_text_for_table
)


class CashFlowGenerator(BaseReportGenerator):
    """Generate Cash Flow PDF reports"""
    
    def generate_cash_flow_report(self, user_data, transactions, start_date=None, end_date=None, tag_filter="all"):
        """Generate Cash Flow statement PDF"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72,
                              topMargin=72, bottomMargin=18)
        
        story = []
        
        # Title
        title = Paragraph("Cash Flow Statement", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 12))
        
        # User Info
        nigerian_time = get_nigerian_time()
        period_text = ""
        if start_date and end_date:
            period_text = f"<b>Period:</b> {start_date.strftime('%B %d, %Y')} to {end_date.strftime('%B %d, %Y')}<br/>"
        
        user_info = f"""
        <b>Name:</b> {user_data.get('firstName', '')} {user_data.get('lastName', '')}<br/>
        <b>TIN:</b> {format_tin_display(user_data.get('tin', ''))}<br/>
        <b>Email:</b> {user_data.get('email', '')}<br/>
        {period_text}
        <b>Report Generated:</b> {nigerian_time.strftime('%B %d, %Y at %H:%M WAT')}
        """
        story.append(Paragraph(user_info, self.styles['InfoText']))
        story.append(Spacer(1, 20))
        
        # Add filter disclaimer (Feb 26, 2026)
        if tag_filter and tag_filter != 'all':
            disclaimer_text = self._get_filter_disclaimer(tag_filter)
            disclaimer = Paragraph(disclaimer_text, self.styles['InfoText'])
            story.append(disclaimer)
            story.append(Spacer(1, 12))

        
        # Calculate cash flows
        operating_inflows = sum(t.get('amount', 0) for t in transactions.get('incomes', []))
        operating_outflows = sum(t.get('amount', 0) for t in transactions.get('expenses', []))
        net_operating = operating_inflows - operating_outflows
        
        # Operating Activities
        story.append(Paragraph("Cash Flow from Operating Activities", self.styles['SectionHeader']))
        operating_data = [
            ['Description', 'Amount (N)'],
            [wrap_text_for_table('Cash Inflows (Income)', 25), format_currency(operating_inflows)],
            [wrap_text_for_table('Cash Outflows (Expenses)', 25), format_currency(-operating_outflows)],
            [wrap_text_for_table('Net Cash from Operations', 25), format_currency(net_operating)]
        ]
        
        operating_table = create_table(operating_data, col_widths=[4*inch, 2*inch])
        operating_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ReportColors.FINANCIAL_GOLDEN),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BACKGROUND', (0, -1), (-1, -1), ReportColors.FINANCIAL_LIGHT),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(operating_table)
        story.append(Spacer(1, 20))
        
        # Summary
        story.append(Paragraph("Summary", self.styles['SectionHeader']))
        summary_text = f"""
        <b>Total Cash Inflows:</b> ₦{safe_float(operating_inflows):,.2f}<br/>
        <b>Total Cash Outflows:</b> ₦{safe_float(operating_outflows):,.2f}<br/>
        <b>Net Cash Flow:</b> ₦{safe_float(net_operating):,.2f}
        """
        story.append(Paragraph(summary_text, self.styles['Normal']))
        
        # Footer
        story.extend(self._build_footer())
        
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def _build_footer(self):
        """Build report footer"""
        footer_text = """
        <i>This cash flow statement is for informational purposes only.<br/>
        Generated by FiCore Mobile App | team@ficoreafrica.com</i>
        """
        elements = []
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(footer_text, self.styles['InfoText']))
        return elements