"""
Test Mode VAS Purchase Simulator
Simulates successful VAS purchases for Google Play review test accounts
"""
from datetime import datetime
from bson import ObjectId
import uuid

def simulate_airtime_purchase(mongo, user_id, network, amount, phone_number):
    """
    Simulate successful airtime purchase for test accounts
    
    Args:
        mongo: MongoDB instance
        user_id: User ID (ObjectId or string)
        network: Network provider (MTN, AIRTEL, GLO, 9MOBILE)
        amount: Airtime amount
        phone_number: Phone number
        
    Returns:
        dict: Simulated success response
    """
    if isinstance(user_id, str):
        user_id = ObjectId(user_id)
    
    transaction_id = f"TEST_AIRTIME_{uuid.uuid4().hex[:12]}"
    reference = f"TEST_REF_{uuid.uuid4().hex[:8]}"
    
    # Create VAS transaction record
    vas_transaction = {
        'transactionId': transaction_id,
        'userId': user_id,
        'type': 'AIRTIME',
        'provider': network,
        'amount': amount,
        'phoneNumber': phone_number,
        'status': 'success',
        'reference': reference,
        'testMode': True,
        'timestamp': datetime.utcnow(),
        'createdAt': datetime.utcnow(),
        'vendStatus': 'SUCCESS',
        'description': f'₦{amount} {network} Airtime (TEST MODE)'
    }
    
    mongo.db.vas_transactions.insert_one(vas_transaction)
    
    # Auto-create expense entry (bookkeeping as by-product)
    expense_id = f"expense_{ObjectId()}"
    expense_entry = {
        'expenseId': expense_id,
        'userId': str(user_id),
        'date': datetime.utcnow(),
        'amount': amount,
        'category': 'Communication',
        'description': f'Airtime - {network} via FiCore (TEST MODE)',
        'paymentMethod': 'VAS Wallet',
        'tag': 'Personal',
        'vasTransactionId': transaction_id,
        'autoGenerated': True,
        'testMode': True,
        'createdAt': datetime.utcnow(),
        'updatedAt': datetime.utcnow(),
        'syncStatus': 'synced'
    }
    
    mongo.db.expenses.insert_one(expense_entry)
    
    print(f'[TEST MODE] Simulated airtime purchase: {network} ₦{amount} -> {phone_number}')
    print(f'[TEST MODE] Transaction ID: {transaction_id}')
    print(f'[TEST MODE] Auto-created expense entry: {expense_id}')
    
    return {
        'success': True,
        'transactionId': transaction_id,
        'reference': reference,
        'vendStatus': 'SUCCESS',
        'description': f'₦{amount} {network} Airtime purchased successfully (TEST MODE)',
        'provider': 'test_mode',
        'vendAmount': amount,
        'commission': 0,
        'productName': f'₦{amount} {network} Airtime',
        'testMode': True
    }

def simulate_data_purchase(mongo, user_id, network, data_plan_code, phone_number, amount, plan_name):
    """
    Simulate successful data purchase for test accounts
    
    Args:
        mongo: MongoDB instance
        user_id: User ID (ObjectId or string)
        network: Network provider
        data_plan_code: Data plan code
        phone_number: Phone number
        amount: Data plan cost
        plan_name: Data plan name (e.g., "5GB Monthly")
        
    Returns:
        dict: Simulated success response
    """
    if isinstance(user_id, str):
        user_id = ObjectId(user_id)
    
    transaction_id = f"TEST_DATA_{uuid.uuid4().hex[:12]}"
    reference = f"TEST_REF_{uuid.uuid4().hex[:8]}"
    
    # Create VAS transaction record
    vas_transaction = {
        'transactionId': transaction_id,
        'userId': user_id,
        'type': 'DATA',
        'provider': network,
        'amount': amount,
        'phoneNumber': phone_number,
        'bundle': plan_name,
        'planCode': data_plan_code,
        'status': 'success',
        'reference': reference,
        'testMode': True,
        'timestamp': datetime.utcnow(),
        'createdAt': datetime.utcnow(),
        'vendStatus': 'SUCCESS',
        'description': f'{plan_name} - {network} (TEST MODE)'
    }
    
    mongo.db.vas_transactions.insert_one(vas_transaction)
    
    # Auto-create expense entry
    expense_id = f"expense_{ObjectId()}"
    expense_entry = {
        'expenseId': expense_id,
        'userId': str(user_id),
        'date': datetime.utcnow(),
        'amount': amount,
        'category': 'Communication',
        'description': f'Data - {plan_name} {network} via FiCore (TEST MODE)',
        'paymentMethod': 'VAS Wallet',
        'tag': 'Personal',
        'vasTransactionId': transaction_id,
        'autoGenerated': True,
        'testMode': True,
        'createdAt': datetime.utcnow(),
        'updatedAt': datetime.utcnow(),
        'syncStatus': 'synced'
    }
    
    mongo.db.expenses.insert_one(expense_entry)
    
    print(f'[TEST MODE] Simulated data purchase: {network} {plan_name} ₦{amount} -> {phone_number}')
    print(f'[TEST MODE] Transaction ID: {transaction_id}')
    print(f'[TEST MODE] Auto-created expense entry: {expense_id}')
    
    return {
        'success': True,
        'transactionId': transaction_id,
        'reference': reference,
        'vendStatus': 'SUCCESS',
        'description': f'{plan_name} - {network} purchased successfully (TEST MODE)',
        'provider': 'test_mode',
        'vendAmount': amount,
        'commission': 0,
        'productName': plan_name,
        'testMode': True
    }

def simulate_electricity_purchase(mongo, user_id, provider, amount, meter_number):
    """
    Simulate successful electricity bill payment for test accounts
    
    Args:
        mongo: MongoDB instance
        user_id: User ID (ObjectId or string)
        provider: Electricity provider (AEDC, IKEDC, etc.)
        amount: Bill amount
        meter_number: Meter number
        
    Returns:
        dict: Simulated success response
    """
    if isinstance(user_id, str):
        user_id = ObjectId(user_id)
    
    transaction_id = f"TEST_ELEC_{uuid.uuid4().hex[:12]}"
    reference = f"TEST_REF_{uuid.uuid4().hex[:8]}"
    token = f"{uuid.uuid4().hex[:16].upper()}"
    
    # Create VAS transaction record
    vas_transaction = {
        'transactionId': transaction_id,
        'userId': user_id,
        'type': 'electricity',
        'provider': provider,
        'amount': amount,
        'meterNumber': meter_number,
        'token': token,
        'status': 'success',
        'reference': reference,
        'testMode': True,
        'timestamp': datetime.utcnow(),
        'createdAt': datetime.utcnow(),
        'vendStatus': 'SUCCESS',
        'description': f'₦{amount} {provider} Electricity (TEST MODE)'
    }
    
    mongo.db.vas_transactions.insert_one(vas_transaction)
    
    # Auto-create expense entry
    expense_id = f"expense_{ObjectId()}"
    expense_entry = {
        'expenseId': expense_id,
        'userId': str(user_id),
        'date': datetime.utcnow(),
        'amount': amount,
        'category': 'Utilities',
        'description': f'Electricity - {provider} via FiCore (TEST MODE)',
        'paymentMethod': 'VAS Wallet',
        'tag': 'Personal',
        'vasTransactionId': transaction_id,
        'autoGenerated': True,
        'testMode': True,
        'createdAt': datetime.utcnow(),
        'updatedAt': datetime.utcnow(),
        'syncStatus': 'synced'
    }
    
    mongo.db.expenses.insert_one(expense_entry)
    
    print(f'[TEST MODE] Simulated electricity payment: {provider} ₦{amount} -> {meter_number}')
    print(f'[TEST MODE] Transaction ID: {transaction_id}')
    print(f'[TEST MODE] Token: {token}')
    print(f'[TEST MODE] Auto-created expense entry: {expense_id}')
    
    return {
        'success': True,
        'transactionId': transaction_id,
        'reference': reference,
        'token': token,
        'vendStatus': 'SUCCESS',
        'description': f'₦{amount} {provider} Electricity purchased successfully (TEST MODE)',
        'provider': 'test_mode',
        'vendAmount': amount,
        'commission': 0,
        'testMode': True
    }
